a=int(input("Enter First number:"))
b=int(input("Enter Second number:"))
print("ADD of A&B:",a+b)
print("SUB of A&B:",a-b)
print("MUL of A&B:",a*b)
print("DIV of A&B:",a/b)
print("Floor DIV of A&B:",a//b)
print("MOD of A&B:",a%b)
print("EXP of A&B:",a**b)